LOGOUT = 1
LOGIN = 2
MESSAGE = 3
BROADCAST = 4
WHOELSE = 5
WHOELSESINCE = 6
BLOCK = 7
UNBLOCK = 8
INVALID_ACTION = 999
NO_MESSAGE_TO_SEND = 888

LOGIN_NO_SUCH_USER = 0
LOGIN_SUCCESS = 1
LOGIN_INVALID_PASSWORD = 2
LOGIN_USER_BLOCKED = 3
LOGIN_USER_ALREADY_LOGGEDIN = 4

LOGOUT_MESSAGE = "SEE YOU. BYE!!"