LOGOUT = 0
LOGIN = 1
MESSAGE = 2
BROADCAST = 3
WHOELSE = 4
WHOELSESINCE = 5
BLOCK = 6
UNBLOCK = 7
ACTION_UNKOWN = 999

LOGIN_NO_SUCH_USER = 0
LOGIN_SUCCESS = 1
LOGIN_INVALID_PASSWORD = 2
LOGIN_USER_BLOCKED = 3
LOGIN_USER_ALREADY_LOGGEDIN = 4